// complains img
import complainOne from "../assets/complain-01.png";
import complainTwo from "../assets/complain-02.png";
import complainThree from "../assets/complain-03.png";
import complainFour from "../assets/complain-04.png";
import complainFive from "../assets/complain-05.png";
export const complainsType = [
  {
    id: 1,
    title: "<div>ملخص</div> تقييم الأضرار",
    img: complainOne,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 2,
    title: "الابلاغ عن حادث",
    img: complainTwo,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 3,
    title: "بلاغ عن احتيال",
    img: complainThree,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 4,
    title: "احقية خصم تامين السيارات",
    img: complainFour,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 5,
    title: "صيانة السيارة",
    img: complainFive,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 6,
    title: "احقية خصم تامين السيارات",
    img: complainFour,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 7,
    title: "<div>ملخص</div> تقييم الأضرار",

    img: complainOne,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 8,
    title: "صيانة السيارة",
    img: complainFive,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 9,
    title: "الابلاغ عن حادث",
    img: complainTwo,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
  {
    id: 10,
    title: "بلاغ عن احتيال",
    img: complainThree,
    complainNumber: [
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#43A7D8",
      },
      {
        num: 44,
        title: "الشكاوي المرفوضة",
        bg: "#FF6A6F",
      },
      {
        num: 150,
        title: "شكاوي تم اعتمادها",
        bg: "#12AA77",
      },
      {
        num: 150,
        title: "شكاوي  جديدة",
        bg: "#FDBE7B",
      },
    ],
    details: [
      {
        num: 1,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 2,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 3,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: false,
      },
      {
        num: 4,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
      {
        num: 5,
        type: "شكوي 1",
        date: "مايو ,4 ,2023",
        city: "الرياض",
        managment: "ادارة الشكاوي",
        status: "تم قبولها",
        bgNormal: true,
      },
    ],
  },
];
